---
- name: install
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - postgresql-9.4-postgis-2.1
    - postgresql-contrib-9.4

- name: enable conf.d configuration
  replace: dest=/etc/postgresql/9.4/main/postgresql.conf regexp="^#include_dir" replace="include_dir"
  notify: restart psql
  
- name: copy conf.d configuration
  copy: src=settings.conf dest=/etc/postgresql/9.4/main/conf.d/
  notify: restart psql
