---
- name: install
  apt: name=nginx update_cache=yes state=present

- name: copy ssl cert
  copy:
    content: '{{ ssl_cert }}'
    dest: /etc/ssl/certs/maps.zoondka.com.crt
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: copy ssl key
  copy:
    content: '{{ ssl_key }}'
    dest: /etc/ssl/private/maps.zoondka.com.key
    owner: root
    group: root
    mode: 0600
  notify: restart nginx

- name: copy configuration
  copy: src= dest=/etc/nginx/
  notify: restart nginx
