---
- name: install
  apt: name=nginx update_cache=yes state=present

- name: copy ssl cert
  copy:
    content: '{{ ssl_cert }}'
    dest: /etc/ssl/certs/maps.zoondka.com.crt
    owner: root
    group: root
    mode: 0644
  register: cert

- name: copy ssl key
  copy:
    content: '{{ ssl_key }}'
    dest: /etc/ssl/private/maps.zoondka.com.key
    owner: root
    group: root
    mode: 0600
  register: key

- name: copy configuration
  copy: src= dest=/etc/nginx/
  register: conf

- name: restart
  when: cert.changed or key.changed or conf.changed
  service: name=nginx state=restarted enabled=yes
