---
- name: provision zoondka maps tile server stack
  hosts: all
  become: yes
  become_method: sudo
  force_handlers: yes
  
  roles:
    - common
    - iptables
    - ssh
    - nginx
    - postgresql
    - java
    - cassandra
    - kartotherian
