# Generates vtiles from database
gen:
  uri: bridge://
  xml:
    npm: ["osm-bright-source", "data.xml"]
  xmlSetDataSource:
    if:
      dbname: gis
      host: ''
      type: postgis
    set:
      user: {var: osmdb-user}
      password: {var: osmdb-pswd}

# View tiles as generated directly from the database
gg:
  public: true
  formats: [png,json,headers,svg,jpeg]
  scales: [1.3, 1.5, 2, 2.6, 3]
  static: true
  maxheight: 2048
  maxwidth: 2048
  uri: vector://
  xml:
    npm: ["osm-bright-style", "project.xml"]
  xmlSetParams:
    source: {ref: gen}

# Cassandra storage
v2:
  uri: cassandra://
  params:
    minzoom: 0
    maxzoom: 15
    keyspace: v2
    cp: 127.0.0.1 
    username: {var: cassandra-user}
    password: {var: cassandra-pswd}
    durablewrite: 0
    createIfMissing: true

# Cassandra storage
v3:
  uri: cassandra://
  params:
    minzoom: 0
    maxzoom: 15
    keyspace: v3
    cp: 127.0.0.1 
    username: {var: cassandra-user}
    password: {var: cassandra-pswd}
    durablewrite: 0
    createIfMissing: true

# Enable overzoom support
oz:
  uri: overzoom://
  params:
    source: {ref: v2}

# OSM map with international labeling - will be used as default
osm-intl:
  public: true
  formats: [png,json,headers,svg,jpeg]
  scales: [1.3, 1.5, 2, 2.6, 3]
  static: true
  maxheight: 2048
  maxwidth: 2048
  uri: vector://
  xml:
    npm: ["osm-bright-style", "project.xml"]
  xmlSetParams:
    source: {ref: oz}

# OSM map without any labels
osm:
  public: true
  pbfsource: oz
  formats: [png,json,headers,svg,jpeg]
  scales: [1.3, 1.5, 2, 2.6, 3]
  static: true
  maxheight: 2048
  maxwidth: 2048
  uri: vector://
  xml:
    npm: ["osm-bright-style", "project.xml"]
  xmlSetParams:
    source: {ref: oz}
  xmlExceptLayers: ['country_label', 'place_label', 'road_label']
