---
- name: install dependencies
  apt: name={{ item }} update_cache=yes
  with_items:
    - build-essential
    - proj-bin
    - libgeos-dev
    - sqlite3
    - nodejs-legacy
    - npm
    - redis-server

- name: set npm root user
  shell: npm -g config set user root

- include: tilerator.yml
- include: kartozoa.yml

- name: reload systemd
  when: kartozoa_service.changed or tilerator_services.changed
  command: systemctl daemon-reload
