---
- name: "tilerator : download"
  git: repo=https://github.com/kartotherian/tilerator.git dest=/srv/tilerator
  register: src

- name: "tilerator : update submodules"
  when: src.changed
  shell: git submodule update --init chdir=/srv/tilerator

- name: "tilerator : install"
  when: src.changed
  shell: npm install -g --production --no-optional chdir=/srv/tilerator

- name: "tilerator : add user"
  user: name=tilerator createhome=no

- name: "tilerator : copy service files"
  copy: src=tilerator/{{ item }} dest=/etc/systemd/system/
  with_items:
    - tilerator.service
    - tilerator-ui.service
  register: tilerator_services

- name: "tilerator : make config dir"
  file: path=/etc/tilerator state=directory
  
- name: "tilerator : copy config"
  copy: src=tilerator/{{ item }} dest=/etc/tilerator/
  with_items:
    - config.yaml
    - config.ui.yaml
    - sources.yaml
  register: conf

- name: "tilerator : add psql user"
  become_user: postgres
  shell: createuser -s tilerator --no-superuser
  ignore_errors: True

- name: "tilerator : add gis database"
  become_user: postgres
  shell: createdb -E UTF8 -T template0 gis
  ignore_errors: True

- name: "tilerator : add hstore & postgis extensions"
  become_user: postgres
  shell: psql -d gis -c 'CREATE EXTENSION hstore; CREATE EXTENSION postgis;'
  ignore_errors: True

- name: "tilerator : grant gis connect privilege to user tilerator"
  become_user: postgres
  shell: psql -d gis -c 'GRANT CONNECT ON DATABASE gis TO tilerator;'

- name: "tilerator : grant gis usage privilege to user tilerator"
  become_user: postgres
  shell: psql -d gis -c 'GRANT USAGE ON SCHEMA public TO tilerator;'

- name: "tilerator : grant gis select privilege to user tilerator"
  become_user: postgres
  shell: psql -d gis -c 'GRANT SELECT ON ALL TABLES IN SCHEMA public TO tilerator;'

- name: "tilerator : grant gis default select privilege to user tilerator"
  become_user: postgres
  shell: psql -d gis -c 'ALTER DEFAULT PRIVILEGES IN SCHEMA public
   GRANT SELECT ON TABLES TO tilerator;'

- name: "tilerator : add osm2pqsql data directory"
  file: path=/srv/data state=directory recurse=yes owner=postgres group=postgres
  
- name: "tilerator : copy osm2pgsql test data"
  copy: src=umbria.pbf dest=/srv/data/

- name: "tilerator : download water polygons"
  get_url: url=http://data.openstreetmapdata.com/water-polygons-split-3857.zip dest=/srv/data/

- name: "tilerator : unzip water polygons"
  unarchive: copy=no src=/srv/data/water-polygons-split-3857.zip dest=/srv/data/

- file: path=/srv/data/water-polygons-split-3857.zip state=absent
