---
- name: install
  copy: src=iptables.service dest=/etc/systemd/system/
  register: service

- name: add user
  user:
    name: iptables
    createhome: no
  
- name: copy configuration
  copy:
    src: iptables
    dest: /etc/
    mode: 0754
    owner: iptables
    group: iptables
  register: conf

- name: reload systemd
  when: service.changed
  command: systemctl daemon-reload

- name: restart
  when: service.changed or conf.changed
  service: name=iptables state=restarted enabled=yes
