---
# TODO: only add if doesn't exist
- name: add DataStax repository to sources
  shell: 'echo "deb http://debian.datastax.com/datastax-ddc 3.4 main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list'

- name: add DataStax repository key to trusted keys
  shell: "curl -k -L https://debian.datastax.com/debian/repo_key | sudo apt-key add -"

- name: install
  apt: name=datastax-ddc update_cache=yes state=present
