---
- name: add DataStax repository to sources
  lineinfile: dest=/etc/apt/sources.list.d/cassandra.sources.list line="deb http://debian.datastax.com/datastax-ddc 3.4 main" create=yes

- name: add DataStax repository key to trusted keys
  apt_key: url=https://debian.datastax.com/debian/repo_key validate_certs=no

- name: install
  apt: name=datastax-ddc update_cache=yes state=present

- name: set resource limits
  copy: src=cassandra.conf dest=/etc/security/limits.d/
  register: limits

- name: restart
  when: limits.changed
  service: name=cassandra state=restarted enabled=yes
  
