# Cassandra storage
v2:
  uri: cassandra://
  params:
    minzoom: 0
    maxzoom: 14
    keyspace: v2
    cp: 127.0.0.1
    durablewrite: 0
    createIfMissing: true

oz:
  uri: overzoom://
  params:
    source: {ref: v2}

# OSM map with international labeling - will be used as default
osm-intl:
  public: true
  pbfsource: oz
  formats: [png,json,headers,svg,jpeg]
  scales: [1.3, 1.5, 2, 2.6, 3]
  static: true
  maxheight: 2048
  maxwidth: 2048
  uri: vector://
  xml:
    npm: ["osm-bright-style", "project.xml"]
  xmlSetParams:
    source: {ref: oz}

# OSM map without any labels
osm:
  public: true
  pbfsource: oz
  formats: [png,json,headers,svg,jpeg]
  scales: [1.3, 1.5, 2, 2.6, 3]
  static: true
  maxheight: 2048
  maxwidth: 2048
  uri: vector://
  xml:
    npm: ["osm-bright-style", "project.xml"]
  xmlSetParams:
    source: {ref: oz}
  xmlExceptLayers: ['country_label', 'place_label', 'poi_label']
