---
- name: make install directory
  file:
    path: /opt/jdk
    state: directory

- name: check version directory
  stat: path=/opt/jdk/jdk1.8.0_77
  register: version_dir
  
- name: download tarball
  when: not version_dir.stat.exists
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u77-b03/jdk-8u77-linux-x64.tar.gz
    headers: Cookie:oraclelicense=accept-securebackup-cookie
    dest: /opt/jdk/

- name: extract
  when: not version_dir.stat.exists
  unarchive:
    src: /opt/jdk/jdk-8u77-linux-x64.tar.gz
    dest: /opt/jdk/
    copy: no

- name: remove tarball
  when: not version_dir.stat.exists
  file:
    path: /opt/jdk/jdk-8u77-linux-x64.tar.gz
    state: absent
    
- name: update java alternatives
  when: not version_dir.stat.exists
  command: update-alternatives --install /usr/bin/java java /opt/jdk/jdk1.8.0_77/bin/java 100

- name: update javac alternatives
  when: not version_dir.stat.exists
  command: update-alternatives --install /usr/bin/javac javac /opt/jdk/jdk1.8.0_77/bin/javac 100
