---
- name: make install directory
  file:
    path: /opt/jdk
    state: directory

- name: check version directory
  stat: path=/opt/jdk/jdk1.8.0_05
  register: version_dir

- set_fact:
    installed: version_dir.stat.exists

- name: download tarball
  when: not installed
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
    headers: Cookie:oraclelicense=accept-securebackup-cookie
    dest: /opt/jdk/

- name: extract
  when: not installed
  unarchive:
    src: /opt/jdk/jdk-8u5-linux-x64.tar.gz
    dest: /opt/jdk/
    copy: no

- name: remove tarball
  when: not installed
  file:
    path: /opt/jdk/jdk-8u5-linux-x64.tar.gz
    state: absent
    
- name: update java alternatives
  when: not installed
  command: update-alternatives --install /usr/bin/java java /opt/jdk/jdk1.8.0_05/bin/java 100

- name: update javac alternatives
  when: not installed
  command: update-alternatives --install /usr/bin/javac javac /opt/jdk/jdk1.8.0_05/bin/javac 100
