---
- name: reboot
  command: shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true

- name: wait for system start
  local_action: wait_for host={{ ansible_host | default(ansible_ssh_host) }} port={{ ansible_port | default(ansible_ssh_port) }} timeout=5 state=started
  become: false
