---
- name: install cpufrequtils
  apt: name=cpufrequtils update_cache=yes state=present
  
- name: set performance governor
  copy: src=cpufrequtils dest=/etc/default/
  notify:
    - reboot
    - wait for system start

- name: set SysFS rotational flag
  shell: "echo 0 > /sys/class/block/sda/queue/rotational"

- name: set noop scheduler
  shell: "echo noop > /sys/block/sda/queue/scheduler"

- name: set read-ahead value
  shell: "echo 8 > /sys/class/block/sda/queue/read_ahead_kb"

- name: disable zone_reclaim_mode
  shell: "echo 0 > /proc/sys/vm/zone_reclaim_mode"

- name: set max map count
  lineinfile: dest=/etc/sysctl.conf  line="vm.max_map_count = 131072"
  register: sysctl

- name: restart sysctl
  when: sysctl.changed
  shell: "sysctl -p"

- name: set blockdev readahead
  shell: "blockdev --setra 128 /dev/sda"

- name: add zoondev user
  user: name=zoondev shell=/bin/bash groups=sudo password={{ zoondev_pass | password_hash('sha512') }}

- name: add neovim repo to sources
  lineinfile: dest=/etc/apt/sources.list line="deb http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu vivid main"

- name: add neovim key
  shell: apt-key adv --recv-keys --keyserver hkp://pgp.mit.edu:80 55F96FCF8231B6DD

- name: install apt system dependencies
  apt: name={{ item }} update_cache=yes
  with_items:
    - unzip 
    - git
    - neovim
